$("#configBtn").click(function(){
    if($("#configBtn")){
        $(".modal-settings").css("display","flex")
    }
});
$("#closeBtn").click(function(){
    if($("#configBtn")){
        $(".modal-settings").css("display","none")
    }
});